// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ConfigDatabaseFile.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Com.Dxll.Proto {

  /// <summary>Holder for reflection information generated from ConfigDatabaseFile.proto</summary>
  public static partial class ConfigDatabaseFileReflection {

    #region Descriptor
    /// <summary>File descriptor for ConfigDatabaseFile.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConfigDatabaseFileReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhDb25maWdEYXRhYmFzZUZpbGUucHJvdG8SDkNvbS5EeGxsLlByb3RvGgpi",
            "dWZmLnByb3RvGgp0ZXN0LnByb3RvImwKDkNvbmZpZ0RhdGFiYXNlEiwKBEJ1",
            "ZmYYASABKAsyHi5Db20uRHhsbC5Qcm90by5idWZmQ29uZmlnRGF0YRIsCgRU",
            "ZXN0GAIgASgLMh4uQ29tLkR4bGwuUHJvdG8udGVzdENvbmZpZ0RhdGFiBnBy",
            "b3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Com.Dxll.Proto.BuffReflection.Descriptor, global::Com.Dxll.Proto.TestReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Dxll.Proto.ConfigDatabase), global::Com.Dxll.Proto.ConfigDatabase.Parser, new[]{ "Buff", "Test" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ConfigDatabase : pb::IMessage<ConfigDatabase> {
    private static readonly pb::MessageParser<ConfigDatabase> _parser = new pb::MessageParser<ConfigDatabase>(() => new ConfigDatabase());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ConfigDatabase> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Dxll.Proto.ConfigDatabaseFileReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigDatabase() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigDatabase(ConfigDatabase other) : this() {
      Buff = other.buff_ != null ? other.Buff.Clone() : null;
      Test = other.test_ != null ? other.Test.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigDatabase Clone() {
      return new ConfigDatabase(this);
    }

    /// <summary>Field number for the "Buff" field.</summary>
    public const int BuffFieldNumber = 1;
    private global::Com.Dxll.Proto.buffConfigData buff_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Com.Dxll.Proto.buffConfigData Buff {
      get { return buff_; }
      set {
        buff_ = value;
      }
    }

    /// <summary>Field number for the "Test" field.</summary>
    public const int TestFieldNumber = 2;
    private global::Com.Dxll.Proto.testConfigData test_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Com.Dxll.Proto.testConfigData Test {
      get { return test_; }
      set {
        test_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ConfigDatabase);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ConfigDatabase other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Buff, other.Buff)) return false;
      if (!object.Equals(Test, other.Test)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (buff_ != null) hash ^= Buff.GetHashCode();
      if (test_ != null) hash ^= Test.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (buff_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Buff);
      }
      if (test_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Test);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (buff_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Buff);
      }
      if (test_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Test);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ConfigDatabase other) {
      if (other == null) {
        return;
      }
      if (other.buff_ != null) {
        if (buff_ == null) {
          buff_ = new global::Com.Dxll.Proto.buffConfigData();
        }
        Buff.MergeFrom(other.Buff);
      }
      if (other.test_ != null) {
        if (test_ == null) {
          test_ = new global::Com.Dxll.Proto.testConfigData();
        }
        Test.MergeFrom(other.Test);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (buff_ == null) {
              buff_ = new global::Com.Dxll.Proto.buffConfigData();
            }
            input.ReadMessage(buff_);
            break;
          }
          case 18: {
            if (test_ == null) {
              test_ = new global::Com.Dxll.Proto.testConfigData();
            }
            input.ReadMessage(test_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
